remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Virtual Nate's website
description: A site for some of my random things.
show_downloads: false
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: "docs/prs-format"
      type: "pages"
    values:
      layout: "prs_wiki"
      table_of_contents: null
